function exp = exp_build_scan_map(varargin) 
    exp = experiment_base('build_scan_map');
        
    exp.environment = grp_obstacles_and_landmarks_from_image('../maps/office.png', 'scale', 0.01);    
    pathPoints = [1.00,   0.50;...
                  1.00, 4.30;...
                  2.60, 4.30;...
                  2.60, 2.70;...
                  6.00, 2.70;... 
                  6.00, 5.10;...
                  7.00, 5.10;...
                  6.00, 5.10;...
                  6.00, 3.30;...
                  7.50, 2.70;...
                  7.50, 0.75;...
                  5.00, 1.50;...
                  2.00, 1.50;...
                  2.00, 0.50];
  
    exp.robot.scanMap = map_scans2d();
    
    exp.robot.platform = model_platform2d_on_path(pathPoints);
    exp.robot.sensors.rangefinder = sensor_rangefinder2d();
    exp.robot.sensors.rangefinder.color = [0.7 0 0];
    
    exp.robot.color = [0.2 0.2 1];
    exp.robot.radius = 0.14;
    
	exp.depends = {'*scanMap'};
    
    exp.display.settings = {'XGrid', 'on', 'YGrid', 'on', 'Layer', 'top', 'XLim', [0 8], 'YLim', [0 6]};    
end